### PR TITLE
Use 32bit CSRs + imafd

### PR DESCRIPTION
**Pull request by troibe**
With https://github.com/enjoy-digital/litex/commit/4f82a36afdccfd030d26bcb49c6fe1017bfb87c2 LiteX is discontinuing their 64bit CSRs therefore we need to use 32bit CSRs in BBL.

### CODE REVIEW

**Comment by troibe** [comment]
@dpetrisko Could you merge this one too?

**Comment by dpetrisko** [comment]
@farzamgl any problems with this?

**Comment by farzamgl** [comment]
I don't see anything of the face of it. Are we actually running riscv-pk on Litex?

**Comment by dpetrisko** [comment]
Yeah I believe opensbi should work with minimal effort, but we’ve only run LiteX on riscv-pk so far

**Comment by troibe** [comment]
Yes riscv-pk is the one currently used. It's the same for Litex+Rocket. Litex+Vexriscv switched to Opensbi sometime ago so I might look into this sometime in the future too...

**Pull request merged**
