### PR TITLE
LiteX support for BlackParrot 

### PR DESCRIPTION
**Pull request by scanakci**
Necessary changes to support LiteX UART for FPGA Linux bootup

### CODE REVIEW

**Comment by dpetrisko** [comment]
@farzamgl what's needed to port this to opensbi?

**Comment by dpetrisko** [comment]
@farzamgl

**Comment by farzamgl** [comment]
Added the blackparrot litex platform to the opensbi code. (https://github.com/black-parrot/opensbi/commit/26df34e11053425a675c799964dbd0031188af2d)
Is this the only LiteX specific change to the firmware @scanakci?

**Comment by troibe** [comment]
@farzamgl @dpetrisko
I need to add some changes that are based on this PR. [freedom-u-sdk](https://github.com/bsg-external/freedom-u-sdk/tree/blackparrot_mods) is already using this unmerged PR which means I can't add any changes unless it gets merged.
Could you merge this so that I can base my changes on it?
Or should I create a new pull request which includes these changes + my own changes?
image

**Comment by dpetrisko** [comment]
we can merge this. We don't really use freedom sdk anymore since we moved off spike for simulation, so I don't think there's a danger

**Pull request merged**
